export const usersConst = {
  REQ_USERS_DATA: 'REQ_USERS_DATA',
  RES_USERS_DATA: 'RES_USERS_DATA',
  ERR_USERS_DATA: 'ERR_USERS_DATA',

  REQ_USER_DATA: 'REQ_USER_DATA',
  RES_USER_DATA: 'RES_USER_DATA',
  ERR_USER_DATA: 'ERR_USER_DATA',

  REQ_USER_EDIT_DATA: 'REQ_USER_EDIT_DATA',
  RES_USER_EDIT_DATA: 'RES_USER_EDIT_DATA',
  ERR_USER_EDIT_DATA: 'ERR_USER_EDIT_DATA',

  REQ_CREATE_USER: 'REQ_CREATE_USER',
  RES_CREATE_USER: 'RES_CREATE_USER',
  ERR_CREATE_USER: 'ERR_CREATE_USER',

  REQ_USER_DEL_DATA: 'REQ_USER_DEL_DATA',
  RES_USER_DEL_DATA: 'RES_USER_DEL_DATA',
  ERR_USER_DEL_DATA: 'ERR_USER_DEL_DATA',

  ERISE_USERS_DATA: 'ERISE_USERS_DATA',
  RESET_USERS_DATA: 'RESET_USERS_DATA',
  FILTER_USERS_DATA: 'FILTER_USERS_DATA',
  SORT_USERS_DATA: 'SORT_USERS_DATA',
}